"use client";

import { useState, useMemo } from "react";

// SBP BSC offices and CDNS branches for prize bond encashment
const SBP_OFFICES = [
  { city: "Karachi", name: "SBP BSC Karachi", address: "I.I. Chundrigar Road, Karachi", lat: 24.8560, lng: 67.0100 },
  { city: "Lahore", name: "SBP BSC Lahore", address: "19-Davis Road, Lahore", lat: 31.5540, lng: 74.3436 },
  { city: "Islamabad", name: "SBP BSC Islamabad", address: "Sector G-5/2, Islamabad", lat: 33.7215, lng: 73.0433 },
  { city: "Rawalpindi", name: "SBP BSC Rawalpindi", address: "The Mall, Rawalpindi", lat: 33.5984, lng: 73.0479 },
  { city: "Peshawar", name: "SBP BSC Peshawar", address: "Khyber Road, Peshawar", lat: 34.0125, lng: 71.5785 },
  { city: "Quetta", name: "SBP BSC Quetta", address: "Jinnah Road, Quetta", lat: 30.1928, lng: 67.0065 },
  { city: "Multan", name: "SBP BSC Multan", address: "Kutchery Road, Multan", lat: 30.1984, lng: 71.4687 },
  { city: "Faisalabad", name: "SBP BSC Faisalabad", address: "Civil Lines, Faisalabad", lat: 31.4187, lng: 73.0791 },
  { city: "Hyderabad", name: "SBP BSC Hyderabad", address: "Thandi Sarak, Hyderabad", lat: 25.3924, lng: 68.3737 },
  { city: "Sialkot", name: "SBP BSC Sialkot", address: "Paris Road, Sialkot", lat: 32.5005, lng: 74.5310 },
  { city: "Sukkur", name: "SBP BSC Sukkur", address: "Military Road, Sukkur", lat: 27.7052, lng: 68.8574 },
  { city: "Muzaffarabad", name: "CDNS Muzaffarabad", address: "Bank Road, Muzaffarabad", lat: 34.3700, lng: 73.4711 },
] as const;

interface ClaimInfo {
  bondNumber: string;
  denomination: number;
  prizePosition: string;
  prizeAmount: number;
  drawDate: string;
  drawNumber: number | null;
}

const TAX_RATES = { filer: 0.15, non_filer: 0.30 } as const;

function getClaimProcess(position: string): { where: string; docs: string[]; timeline: string } {
  if (position === "1st" || position === "2nd") {
    return {
      where: "SBP Banking Services Corporation (BSC) office",
      docs: [
        "Original winning prize bond",
        "CNIC (original + photocopy)",
        "Claim form PB-23C (filled)",
        "Two passport-size photographs",
        "Bank account details (for transfer)",
      ],
      timeline: "1st prize: 2-4 weeks. 2nd prize: 1-2 weeks.",
    };
  }
  return {
    where: "Any SBP BSC office or National Savings Centre",
    docs: [
      "Original winning prize bond",
      "CNIC (original + photocopy)",
      "For amounts over Rs. 50,000: Claim form PB-23C",
    ],
    timeline: "Usually same day or within 3-5 working days.",
  };
}

function haversineDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) *
    Math.sin(dLng / 2) * Math.sin(dLng / 2);
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

export function ClaimAssistant({ claimInfo, onClose }: { claimInfo: ClaimInfo; onClose: () => void }) {
  const [filerStatus, setFilerStatus] = useState<"filer" | "non_filer">("filer");
  const [userLocation, setUserLocation] = useState<{ lat: number; lng: number } | null>(null);
  const [locating, setLocating] = useState(false);

  const taxRate = TAX_RATES[filerStatus];
  const taxAmount = Math.round(claimInfo.prizeAmount * taxRate);
  const netAmount = claimInfo.prizeAmount - taxAmount;

  const claimProcess = getClaimProcess(claimInfo.prizePosition);

  const sortedOffices = useMemo(() => {
    if (!userLocation) return SBP_OFFICES.slice();
    return [...SBP_OFFICES].sort((a, b) => {
      const distA = haversineDistance(userLocation.lat, userLocation.lng, a.lat, a.lng);
      const distB = haversineDistance(userLocation.lat, userLocation.lng, b.lat, b.lng);
      return distA - distB;
    });
  }, [userLocation]);

  const handleLocate = () => {
    if (!navigator.geolocation) return;
    setLocating(true);
    navigator.geolocation.getCurrentPosition(
      (pos) => {
        setUserLocation({ lat: pos.coords.latitude, lng: pos.coords.longitude });
        setLocating(false);
      },
      () => setLocating(false),
      { timeout: 10_000 }
    );
  };

  const handleGeneratePDF = async () => {
    const [{ jsPDF }] = await Promise.all([import("jspdf")]);
    const doc = new jsPDF("p", "pt", "a4");

    // Header
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 595, 70, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Prize Bond Claim Guide", 40, 42);
    doc.setFontSize(9);
    doc.text("Generated by BondCheck PRO", 545, 42, { align: "right" });

    // Win details
    let y = 100;
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Winning Bond Details", 40, y);
    y += 25;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const details = [
      ["Bond Number:", claimInfo.bondNumber],
      ["Denomination:", `Rs. ${claimInfo.denomination.toLocaleString()}`],
      ["Prize Position:", claimInfo.prizePosition],
      ["Prize Amount (Gross):", `Rs. ${claimInfo.prizeAmount.toLocaleString()}`],
      ["Tax Rate:", `${(taxRate * 100).toFixed(0)}% (${filerStatus === "filer" ? "Filer" : "Non-Filer"})`],
      ["Tax Deduction:", `Rs. ${taxAmount.toLocaleString()}`],
      ["Net Amount:", `Rs. ${netAmount.toLocaleString()}`],
      ["Draw Date:", claimInfo.drawDate],
    ];

    if (claimInfo.drawNumber) {
      details.push(["Draw Number:", `#${claimInfo.drawNumber}`]);
    }

    for (const [label, value] of details) {
      doc.setFont("helvetica", "bold");
      doc.text(label, 40, y);
      doc.setFont("helvetica", "normal");
      doc.text(value, 200, y);
      y += 18;
    }

    // Claim process
    y += 15;
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("How to Claim", 40, y);
    y += 25;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Where: ${claimProcess.where}`, 40, y);
    y += 20;
    doc.text("Required Documents:", 40, y);
    y += 18;
    for (const docItem of claimProcess.docs) {
      doc.text(`  - ${docItem}`, 50, y);
      y += 16;
    }
    y += 10;
    doc.text(`Timeline: ${claimProcess.timeline}`, 40, y);

    // Nearest offices
    y += 30;
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("SBP BSC Offices", 40, y);
    y += 20;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    for (const office of sortedOffices.slice(0, 5)) {
      doc.text(`${office.name} - ${office.address}`, 40, y);
      y += 14;
    }

    doc.save(`ClaimGuide_${claimInfo.bondNumber}_${Date.now()}.pdf`);
  };

  return (
    <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4" onClick={onClose}>
      <div
        className="bg-white rounded-sm border border-gray-200 max-w-lg w-full max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="bg-[#0f172a] text-white px-6 py-4 flex items-center justify-between">
          <div>
            <h2 className="text-sm font-semibold">Prize Claim Assistant</h2>
            <p className="text-[10px] text-gray-400 mt-0.5">Step-by-step guide to claim your prize</p>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="p-6 space-y-6">
          {/* Win Summary */}
          <div className="bg-emerald-50 border border-emerald-200 rounded-sm p-4">
            <div className="flex items-center justify-between mb-2">
              <span className="text-[10px] font-semibold text-emerald-700 uppercase tracking-wider">Winning Bond</span>
              <span className="text-xs font-mono font-bold text-emerald-800">{claimInfo.bondNumber}</span>
            </div>
            <div className="grid grid-cols-2 gap-3 text-xs">
              <div>
                <span className="text-emerald-600">Denomination</span>
                <p className="font-mono font-semibold">Rs. {claimInfo.denomination.toLocaleString()}</p>
              </div>
              <div>
                <span className="text-emerald-600">{claimInfo.prizePosition} Prize</span>
                <p className="font-mono font-semibold">Rs. {claimInfo.prizeAmount.toLocaleString()}</p>
              </div>
            </div>
          </div>

          {/* Tax Breakdown */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <span className="text-[10px] font-semibold text-gray-500 uppercase tracking-wider">Tax Breakdown</span>
              <div className="flex items-center bg-gray-100 rounded-sm overflow-hidden">
                <button
                  onClick={() => setFilerStatus("filer")}
                  className={`px-2.5 py-1 text-[10px] font-medium transition-colors ${
                    filerStatus === "filer" ? "bg-[#0f172a] text-white" : "text-gray-500"
                  }`}
                >
                  Filer (15%)
                </button>
                <button
                  onClick={() => setFilerStatus("non_filer")}
                  className={`px-2.5 py-1 text-[10px] font-medium transition-colors ${
                    filerStatus === "non_filer" ? "bg-[#0f172a] text-white" : "text-gray-500"
                  }`}
                >
                  Non-Filer (30%)
                </button>
              </div>
            </div>
            <div className="border border-gray-200 rounded-sm divide-y divide-gray-100">
              <div className="flex justify-between px-4 py-2.5 text-xs">
                <span className="text-gray-500">Gross Prize</span>
                <span className="font-mono">Rs. {claimInfo.prizeAmount.toLocaleString()}</span>
              </div>
              <div className="flex justify-between px-4 py-2.5 text-xs">
                <span className="text-gray-500">Tax ({(taxRate * 100).toFixed(0)}%)</span>
                <span className="font-mono text-red-500">- Rs. {taxAmount.toLocaleString()}</span>
              </div>
              <div className="flex justify-between px-4 py-2.5 text-xs bg-gray-50">
                <span className="font-semibold">Net Payout</span>
                <span className="font-mono font-bold text-emerald-600">Rs. {netAmount.toLocaleString()}</span>
              </div>
            </div>
            {filerStatus === "non_filer" && (
              <p className="text-[10px] text-amber-600 mt-2">
                As a filer you&apos;d save Rs. {(taxAmount - Math.round(claimInfo.prizeAmount * 0.15)).toLocaleString()}. Register at iris.fbr.gov.pk
              </p>
            )}
          </div>

          {/* Claim Process */}
          <div>
            <span className="text-[10px] font-semibold text-gray-500 uppercase tracking-wider block mb-3">How to Claim</span>
            <div className="space-y-2">
              <div className="flex gap-3 text-xs">
                <span className="w-5 h-5 rounded-full bg-[#0f172a] text-white flex items-center justify-center text-[10px] font-bold shrink-0">1</span>
                <p className="text-gray-600">Visit: <span className="font-semibold text-gray-800">{claimProcess.where}</span></p>
              </div>
              <div className="flex gap-3 text-xs">
                <span className="w-5 h-5 rounded-full bg-[#0f172a] text-white flex items-center justify-center text-[10px] font-bold shrink-0">2</span>
                <div className="text-gray-600">
                  <p className="mb-1">Bring these documents:</p>
                  <ul className="space-y-0.5">
                    {claimProcess.docs.map((d, i) => (
                      <li key={i} className="flex items-start gap-1.5">
                        <span className="text-gray-300 mt-px">-</span>
                        <span>{d}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
              <div className="flex gap-3 text-xs">
                <span className="w-5 h-5 rounded-full bg-[#0f172a] text-white flex items-center justify-center text-[10px] font-bold shrink-0">3</span>
                <p className="text-gray-600">{claimProcess.timeline}</p>
              </div>
            </div>
          </div>

          {/* Nearest Offices */}
          <div>
            <div className="flex items-center justify-between mb-3">
              <span className="text-[10px] font-semibold text-gray-500 uppercase tracking-wider">Nearest Offices</span>
              <button
                onClick={handleLocate}
                disabled={locating}
                className="text-[10px] text-[#0f172a] font-medium hover:underline disabled:opacity-50"
              >
                {locating ? "Locating..." : userLocation ? "Re-locate" : "Use my location"}
              </button>
            </div>
            <div className="space-y-2 max-h-40 overflow-y-auto">
              {sortedOffices.slice(0, 5).map((office) => {
                const dist = userLocation
                  ? haversineDistance(userLocation.lat, userLocation.lng, office.lat, office.lng)
                  : null;
                return (
                  <div key={office.city} className="flex items-center justify-between border border-gray-100 rounded-sm px-3 py-2">
                    <div>
                      <p className="text-xs font-semibold">{office.name}</p>
                      <p className="text-[10px] text-gray-400">{office.address}</p>
                    </div>
                    {dist != null && (
                      <span className="text-[10px] font-mono text-gray-400 shrink-0 ml-2">
                        {dist < 1 ? `${Math.round(dist * 1000)}m` : `${dist.toFixed(0)}km`}
                      </span>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-3">
            <button
              onClick={handleGeneratePDF}
              className="flex-1 bg-[#0f172a] text-white text-xs font-medium py-2.5 px-4 rounded-sm hover:bg-[#1e293b] transition-colors"
            >
              Download Claim Guide (PDF)
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2.5 text-xs font-medium text-gray-500 border border-gray-200 rounded-sm hover:bg-gray-50 transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
